using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using PinballWizard.Application.Persistence;
using PinballWizard.Core.Domain;
using PinballWizard.Core.Models;

namespace PinballWizard.Cli.Commands;

// Operator-gated capture verbs that write fixtures used by the Wave-2 regression gate.
//
// --capture-golden-set:
//   Streams scraped_documents_raw where link_status in (Linked, ManuallyLinked) and
//   writes a JSON fixture with one entry per (document, machine) fan-out pair. Read-only.
//
// --capture-reconciler-parity:
//   Streams all machines from the machines container, records ManufacturerSlugs per machine,
//   and writes a per-manufacturer count snapshot. Read-only.
//
// Both write into tests/PinballWizard.Application.Tests/Fixtures/ so the replay tests can
// load the fixture and run offline (no Cosmos) against the captured data.
internal static class CaptureGoldenSetCommand
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    internal static async Task RunGoldenLinkSetAsync(
        IServiceProvider services,
        CancellationToken cancellationToken)
    {
        var rawRepo = services.GetService<IRawDocumentRepository>();
        var scrapedRepo = services.GetService<IScrapedDocumentRepository>();
        if (rawRepo is null || scrapedRepo is null)
        {
            Console.Error.WriteLine(
                "--capture-golden-set requires Cosmos to be configured. Set ConnectionStrings:cosmos " +
                "(Aspire-injected) or Cosmos:AccountEndpoint (Managed Identity against a deployed account).");
            Environment.ExitCode = 2;
            return;
        }

        Console.WriteLine("Streaming linked documents from scraped_documents_raw...");

        var entries = new List<GoldenLinkEntry>();
        var docCount = 0;
        var documentsWithoutFanOut = 0;

        await foreach (var raw in rawRepo.StreamByStatusAsync(
            [LinkStatus.Linked, LinkStatus.ManuallyLinked], cancellationToken))
        {
            docCount++;
            var fanOutCount = 0;

            // The authoritative document→machine binding is the scraped_documents fan-out
            // row, NOT raw.LinkedMachineIds. Despite its name and comment, that field is
            // never written by the linker — nothing in src/ assigns it on the Cosmos wire
            // model, and live `link_status: "linked"` documents all carry an empty array.
            // Capturing from it produced a 543-document, 0-entry fixture that left the
            // Wave-2 gate unarmed. The dead field itself is tracked in #800.
            await foreach (var machineId in scrapedRepo.StreamByDocumentIdAsync(raw.DocumentId, cancellationToken))
            {
                fanOutCount++;
                entries.Add(new GoldenLinkEntry
                {
                    DocumentId = raw.DocumentId,
                    FileUrl = raw.Source.FileUrl,
                    SourceType = raw.Source.SourceType.ToString(),
                    GameSlug = raw.Game?.Slug,
                    DocumentType = raw.DocumentType.ToString(),
                    ManufacturerKey = raw.Manufacturer,
                    ExpectedMachineId = machineId,
                });
            }

            if (fanOutCount == 0)
            {
                documentsWithoutFanOut++;
            }
        }

        var capturedAt = DateTimeOffset.UtcNow;
        var fixture = new GoldenLinkSetFixture
        {
            CapturedAt = capturedAt,
            Source = "live Cosmos scraped_documents_raw (link_status in Linked, ManuallyLinked) "
                + "joined to scraped_documents fan-out rows",
            DocumentCount = docCount,
            EntryCount = entries.Count,
            Entries = entries,
        };

        var outputDir = Path.Combine("tests", "PinballWizard.Application.Tests", "Fixtures", "Linking");
        Directory.CreateDirectory(outputDir);

        var fixturePath = Path.Combine(outputDir, "golden-link-set.captured.json");
        await File.WriteAllTextAsync(fixturePath, JsonSerializer.Serialize(fixture, JsonOptions), cancellationToken);

        var captureMd = $"""
            # Golden Link Set — Capture Record

            This file was generated by `--capture-golden-set` against live Cosmos.
            The fixture it accompanies (`golden-link-set.captured.json`) is the Wave-2
            regression gate: `GoldenLinkSetReplayTests` reads it and asserts the new
            resolver reproduces every binding without mis-attribution.

            ## Capture details

            | Field | Value |
            |---|---|
            | Source | live Cosmos `scraped_documents_raw` (link_status = Linked / ManuallyLinked), joined to `scraped_documents` fan-out rows |
            | Captured at | {capturedAt:O} |
            | Documents | {docCount} |
            | Fan-out entries | {entries.Count} |
            | Documents with NO fan-out row | {documentsWithoutFanOut} |

            A document counted in the last row is marked linked but has no
            `scraped_documents` row, so it contributes nothing to the gate. A non-zero
            value is not fatal, but it means the corpus and the fan-out container
            disagree — worth investigating before treating this fixture as a baseline.

            ## What the replay test checks

            For each entry, the test rebuilds a Pending `RawDocumentRecord` from the captured
            fields and runs it through the current `DocumentLinker`. It then checks:
            - `linked → different machine` = BLOCKING (mis-attribution)
            - `linked → needs_review` (null MachineId) = reportable only — the mock catalog
              only seeds slug-resolvable machines, so filename/page-text tiers return nothing
            - `not_in_catalog → linked` = a WIN (reported, not failed)

            ## To recapture

            ```bash
            export AZURE_TOKEN_CREDENTIALS=dev
            export Cosmos__AccountEndpoint="https://pinwiz-cosmos-dev-buutj.documents.azure.com:443/"
            dotnet run --project src/PinballWizard.Cli -c Release -- --capture-golden-set
            ```

            Re-run only after a deliberate re-link that you want as the new baseline.
            """;
        await File.WriteAllTextAsync(Path.Combine(outputDir, "CAPTURE.md"), captureMd, cancellationToken);

        Console.WriteLine();
        Console.WriteLine(
            $"--capture-golden-set complete: {docCount} documents, {entries.Count} fan-out entries "
            + $"({documentsWithoutFanOut} linked document(s) had no fan-out row) → {fixturePath}");
    }

    internal static async Task RunReconcilerParityAsync(
        IServiceProvider services,
        CancellationToken cancellationToken)
    {
        var machineRepo = services.GetService<IMachineRepository>();
        if (machineRepo is null)
        {
            Console.Error.WriteLine(
                "--capture-reconciler-parity requires Cosmos to be configured. Set ConnectionStrings:cosmos " +
                "(Aspire-injected) or Cosmos:AccountEndpoint (Managed Identity against a deployed account).");
            Environment.ExitCode = 2;
            return;
        }

        Console.WriteLine("Streaming all machines from Cosmos to capture ManufacturerSlugs state...");

        var slugEntries = new List<ReconcilerParityEntry>();
        var perManufacturer = new Dictionary<string, (int MachineCount, int SluggedCount)>(StringComparer.Ordinal);
        var totalMachines = 0;

        await foreach (var machine in machineRepo.StreamAllAsync(cancellationToken))
        {
            totalMachines++;
            var mfr = machine.PartitionKey;
            perManufacturer.TryGetValue(mfr, out var counts);

            var hasSlug = false;
            foreach (var (mfrKey, slug) in machine.ManufacturerSlugs)
            {
                if (!string.IsNullOrWhiteSpace(slug))
                {
                    slugEntries.Add(new ReconcilerParityEntry
                    {
                        MachineId = machine.Id,
                        Title = machine.Title,
                        ManufacturerKey = mfrKey,
                        Slug = slug,
                    });
                    hasSlug = true;
                }
            }

            perManufacturer[mfr] = (counts.MachineCount + 1, counts.SluggedCount + (hasSlug ? 1 : 0));
        }

        var capturedAt = DateTimeOffset.UtcNow;
        var manufacturerStats = perManufacturer
            .OrderBy(kv => kv.Key)
            .ToDictionary(
                kv => kv.Key,
                kv => new ManufacturerSlugStat { MachineCount = kv.Value.MachineCount, SluggedCount = kv.Value.SluggedCount });

        var fixture = new ReconcilerParityFixture
        {
            CapturedAt = capturedAt,
            Source = "live Cosmos machines container",
            TotalMachines = totalMachines,
            TotalSlugged = slugEntries.Count,
            ManufacturerStats = manufacturerStats,
            Entries = slugEntries,
        };

        var outputDir = Path.Combine("tests", "PinballWizard.Application.Tests", "Fixtures", "Sync");
        Directory.CreateDirectory(outputDir);

        var fixturePath = Path.Combine(outputDir, "reconciler-parity.captured.json");
        await File.WriteAllTextAsync(fixturePath, JsonSerializer.Serialize(fixture, JsonOptions), cancellationToken);

        var statRows = manufacturerStats
            .Select(kv => $"| {kv.Key} | {kv.Value.MachineCount} | {kv.Value.SluggedCount} |");
        var captureMd = $"""
            # Reconciler Parity Snapshot — Capture Record

            This file was generated by `--capture-reconciler-parity` against live Cosmos.
            The fixture it accompanies (`reconciler-parity.captured.json`) is the Wave-2
            regression gate: `ReconcilerParityReplayTests` seeds a mock machine catalog from
            the captured slugs and asserts the reconciler algorithm still matches them correctly.

            ## Capture details

            | Field | Value |
            |---|---|
            | Source | live Cosmos `machines` container |
            | Captured at | {capturedAt:O} |
            | Total machines | {totalMachines} |
            | Machines with slugs | {slugEntries.Count} |

            ## Manufacturer breakdown

            | Manufacturer | Total machines | Slugged |
            |---|---|---|
            {string.Join("\n", statRows)}

            ## What the replay test checks

            The test seeds `IMachineRepository.StreamByManufacturerAsync` with the captured
            machines and builds a synthetic `GameCatalog` matching those slugs. It then runs
            `ScraperReconciliationService.ReconcileAsync` and asserts `MatchedBySlug` is at
            least the number of DISTINCT (manufacturer, slug) pairs — not the raw entry
            count, since editions legitimately share a slug and collapse into one game.
            Any regression in the slug-matching algorithm — a
            normalization change, a wrong-key lookup, a missing manufacturer prefix — shows up
            as a match-count drop.

            ## To recapture

            ```bash
            export AZURE_TOKEN_CREDENTIALS=dev
            export Cosmos__AccountEndpoint="https://pinwiz-cosmos-dev-buutj.documents.azure.com:443/"
            dotnet run --project src/PinballWizard.Cli -c Release -- --capture-reconciler-parity
            ```
            """;
        await File.WriteAllTextAsync(Path.Combine(outputDir, "CAPTURE.md"), captureMd, cancellationToken);

        Console.WriteLine();
        Console.WriteLine(
            $"--capture-reconciler-parity complete: {totalMachines} machines, {slugEntries.Count} slug entries → {fixturePath}");
    }
}

// ── Fixture data types ────────────────────────────────────────────────────────
// Serialized to JSON by the capture verbs; parallel read-side types live in
// the Application.Tests project so no cross-project dependency is introduced.

internal sealed class GoldenLinkEntry
{
    public string DocumentId { get; init; } = string.Empty;
    public string FileUrl { get; init; } = string.Empty;
    public string SourceType { get; init; } = string.Empty;
    public string? GameSlug { get; init; }
    public string DocumentType { get; init; } = string.Empty;
    public string? ManufacturerKey { get; init; }
    public string ExpectedMachineId { get; init; } = string.Empty;
}

internal sealed class GoldenLinkSetFixture
{
    public DateTimeOffset CapturedAt { get; init; }
    public string Source { get; init; } = string.Empty;
    public int DocumentCount { get; init; }
    public int EntryCount { get; init; }
    public List<GoldenLinkEntry> Entries { get; init; } = [];
}

internal sealed class ReconcilerParityEntry
{
    public string MachineId { get; init; } = string.Empty;
    public string Title { get; init; } = string.Empty;
    public string ManufacturerKey { get; init; } = string.Empty;
    public string Slug { get; init; } = string.Empty;
}

internal sealed class ManufacturerSlugStat
{
    public int MachineCount { get; init; }
    public int SluggedCount { get; init; }
}

internal sealed class ReconcilerParityFixture
{
    public DateTimeOffset CapturedAt { get; init; }
    public string Source { get; init; } = string.Empty;
    public int TotalMachines { get; init; }
    public int TotalSlugged { get; init; }
    public Dictionary<string, ManufacturerSlugStat> ManufacturerStats { get; init; } = [];
    public List<ReconcilerParityEntry> Entries { get; init; } = [];
}
