#requires -Version 7.0
<#
.SYNOPSIS
    Imports the Cloudflare Origin CA certificate (+ private key) into Azure Key Vault
    so the Wizard Container App ingress can present it on its custom domain.

.DESCRIPTION
    The Origin CA cert and key are generated by the infra/cloudflare OpenTofu stack and
    exposed as the sensitive outputs `origin_certificate_pem` and `origin_private_key_pem`
    (see infra/cloudflare/outputs.tf). They are NOT in source control and NOT (until this
    script runs) in Key Vault — despite older wording in docs/cloudflare-setup.md.

    This script reads those two outputs, packages them into a PKCS#12/PFX with openssl, and
    imports that as a Key Vault *certificate* object. PFX is Key Vault's native cert+key
    container and the format every Microsoft sample uses; it avoids the constraints KV places
    on PEM import (key must be PKCS#8, UNIX line endings, cert-before-key — see the KV docs
    "Formats of import we support"). The PFX is protected by an ephemeral password that is
    never logged or persisted.

    The resulting cert's backing secret URI
    (https://<vault>.vault.azure.net/secrets/<CertName>) is what the Bicep
    `Microsoft.App/managedEnvironments/certificates` resource references via
    `certificateKeyVaultProperties.keyVaultUrl`. See ADR-0038.

    Idempotent: if the named cert already exists in the vault with the same SHA-1
    thumbprint, the import is skipped.

.PARAMETER KeyVaultName
    Target Key Vault. Defaults to the dev vault `pinwiz-kv-dev-buutj`.

.PARAMETER CertName
    Key Vault certificate name. Must match the Bicep `keyVaultUrl` secret segment.
    Defaults to `cloudflare-origin-pinwiz`.

.PARAMETER CloudflareTfDir
    Directory of the Cloudflare OpenTofu stack whose state holds the cert outputs.
    Defaults to `infra/cloudflare` relative to the repo root. The stack must be
    initialized (`tofu init`) and its state reachable from this machine.

.PARAMETER TofuExe
    Path to the tofu (or terraform) executable. Defaults to `tofu` on PATH.

.EXAMPLE
    pwsh -File infra/scripts/Import-OriginCaCertToKeyVault.ps1

.NOTES
    PERSONAL SUBSCRIPTION ONLY. Run only against the pinwiz.ai sub (b1f33f17-...) in an
    isolated az context. Never against the work tenant. (Locked invariant #5 / ADR-0010.)
    The cert and key transit local temp files that are securely removed in the finally
    block; key material is never written to logs.

    PREREQUISITE — Key Vault data-plane RBAC. Importing a certificate OBJECT requires the
    caller to hold "Key Vault Certificates Officer" on the vault. The Bicep dev-RBAC grants
    the developer "Key Vault Secrets Officer" (sufficient to READ the backing secret) but
    NOT certificate write. Grant it once (operator is sub Owner) before first import:
      az role assignment create --assignee <your-object-id> ``
        --role "Key Vault Certificates Officer" ``
        --scope /subscriptions/<sub>/resourceGroups/rg-pinwiz-shared-dev/providers/Microsoft.KeyVault/vaults/pinwiz-kv-dev-buutj
    This is a one-time bootstrap (not codified in Bicep: the wizardOriginCert resource and a
    Bicep role grant would form a circular dependency on a fresh environment). See ADR-0038.
#>
[CmdletBinding()]
param(
    [string]$KeyVaultName    = 'pinwiz-kv-dev-buutj',
    [string]$CertName        = 'cloudflare-origin-pinwiz',
    [string]$CloudflareTfDir = (Join-Path $PSScriptRoot '..' 'cloudflare'),
    [string]$TofuExe         = 'tofu'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Step { param([string]$Message) Write-Host "==> $Message" -ForegroundColor Cyan }

# --- Preconditions -----------------------------------------------------------
if (-not (Get-Command $TofuExe -ErrorAction SilentlyContinue)) {
    throw "Tofu executable '$TofuExe' not found on PATH. Pass -TofuExe with the full path."
}
if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    throw "Azure CLI 'az' not found on PATH."
}
# OpenSSL — package the cert + key into a PKCS#12/PFX for Key Vault import.
# Detect via PATH, else derive from the Git for Windows install (git is on PATH;
# openssl ships under <git-root>\usr\bin), else common fallbacks. (Null-guarded
# for StrictMode: (Get-Command ...).Source throws on $null under StrictMode.)
$opensslExe = $null
$opensslCmd = Get-Command openssl -ErrorAction SilentlyContinue
if ($opensslCmd) { $opensslExe = $opensslCmd.Source }
if (-not $opensslExe) {
    $gitCmd = Get-Command git -ErrorAction SilentlyContinue
    if ($gitCmd) {
        $gitRoot = Split-Path (Split-Path $gitCmd.Source -Parent) -Parent
        foreach ($rel in @('usr\bin\openssl.exe', 'mingw64\bin\openssl.exe')) {
            $cand = Join-Path $gitRoot $rel
            if (Test-Path -LiteralPath $cand) { $opensslExe = $cand; break }
        }
    }
}
if (-not $opensslExe) {
    foreach ($cand in @(
            (Join-Path $env:ProgramFiles 'Git\usr\bin\openssl.exe'),
            (Join-Path ${env:ProgramFiles(x86)} 'Git\usr\bin\openssl.exe'))) {
        if ($cand -and (Test-Path -LiteralPath $cand)) { $opensslExe = $cand; break }
    }
}
if (-not $opensslExe) {
    throw "openssl not found — needed to package the Origin CA cert+key as a PFX for Key Vault import. Git for Windows bundles it under '<git-root>\usr\bin\openssl.exe'; add it to PATH or install OpenSSL."
}
Write-Host "Using openssl: $opensslExe" -ForegroundColor DarkGray
if (-not (Test-Path -LiteralPath $CloudflareTfDir)) {
    throw "Cloudflare tofu directory not found: $CloudflareTfDir"
}

# Guard: confirm we are NOT pointed at the work subscription. The personal sub is the
# only acceptable target (ADR-0010). We check the *name* contains the work marker and
# refuse; the positive id check is left to the operator's isolated context.
$acctJson = az account show -o json 2>$null
if ($LASTEXITCODE -ne 0 -or -not $acctJson) {
    throw "Not logged in to Azure (az account show failed). Authenticate to the personal pinwiz.ai sub in an isolated context first."
}
$acct = $acctJson | ConvertFrom-Json
if ($acct.name -match 'APS' -or $acct.name -match 'Advantage') {
    throw "Active subscription is '$($acct.name)' — that looks like the WORK tenant. Switch to the personal pinwiz.ai sub before running. (ADR-0010)"
}
Write-Step "Active subscription: $($acct.name) ($($acct.id))"

$tmpDir  = Join-Path ([System.IO.Path]::GetTempPath()) ("origin-ca-" + [System.Guid]::NewGuid().ToString('N'))
$null    = New-Item -ItemType Directory -Path $tmpDir
$keyPath = Join-Path $tmpDir 'origin.key'
$crtPath = Join-Path $tmpDir 'origin.crt'
$pfxPath = Join-Path $tmpDir 'origin.pfx'

try {
    # --- Pull cert + key from tofu state ------------------------------------
    Write-Step "Reading Origin CA cert + key from tofu state in $CloudflareTfDir"
    # `tofu output -raw` of a multi-line PEM is captured by PowerShell as a string
    # ARRAY (one element per line); join it back with newlines so the on-disk PEM
    # keeps its line breaks (openssl/KV reject a PEM collapsed onto one line).
    $certPem = (& $TofuExe "-chdir=$CloudflareTfDir" output -raw origin_certificate_pem) -join "`n"
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($certPem)) {
        throw "Failed to read 'origin_certificate_pem' from tofu output. Is the stack initialized and state reachable?"
    }
    $keyPem = (& $TofuExe "-chdir=$CloudflareTfDir" output -raw origin_private_key_pem) -join "`n"
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($keyPem)) {
        throw "Failed to read 'origin_private_key_pem' from tofu output."
    }

    # Write with no BOM; restrict ACLs as best-effort on Windows.
    [System.IO.File]::WriteAllText($crtPath, $certPem)
    [System.IO.File]::WriteAllText($keyPath, $keyPem)

    # --- Idempotency: compare against any existing KV cert thumbprint -------
    # Parse the leaf cert from the PEM via manual base64->DER decode. (Avoids
    # X509Certificate2.CreateFromPem, whose ReadOnlySpan<char> overloads do not
    # bind cleanly from a PowerShell [string] on some pwsh/.NET combinations.)
    $certB64 = [regex]::Match(
        $certPem,
        '(?s)-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----'
    ).Groups[1].Value -replace '\s', ''
    if ([string]::IsNullOrWhiteSpace($certB64)) {
        throw "Could not find a CERTIFICATE block in origin_certificate_pem output."
    }
    $certDer = [Convert]::FromBase64String($certB64)
    $newCert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($certDer)
    $newThumb = $newCert.Thumbprint   # hex SHA-1, upper-case
    Write-Step "Origin CA cert subject='$($newCert.Subject)' notAfter='$($newCert.NotAfter.ToString('u'))' thumbprint=$newThumb"

    $existingJson = az keyvault certificate show --vault-name $KeyVaultName --name $CertName -o json 2>$null
    if ($LASTEXITCODE -eq 0 -and $existingJson) {
        $existing = $existingJson | ConvertFrom-Json
        # KV returns x509Thumbprint as base64(SHA-1). Convert ours to the same shape.
        $newThumbB64 = [Convert]::ToBase64String($newCert.GetCertHash())
        if ($existing.x509Thumbprint -eq $newThumbB64) {
            Write-Step "Key Vault already holds '$CertName' with matching thumbprint — nothing to do."
            $secretUri = "https://$KeyVaultName.vault.azure.net/secrets/$CertName"
            Write-Host "Secret URI (for Bicep keyVaultUrl): $secretUri" -ForegroundColor Green
            return
        }
        Write-Step "Existing '$CertName' has a different thumbprint — importing a new version."
    }
    else {
        Write-Step "No existing '$CertName' in $KeyVaultName — importing for the first time."
    }

    # --- Package as PFX and import (documented canonical path) --------------
    # Key Vault's PEM import requires the key in PKCS#8, UNIX (\n) line endings,
    # and cert-before-key ordering (KV docs, "Formats of import we support"). A
    # PKCS#12/PFX sidesteps all three: it is KV's native cert+key container and the
    # format every Microsoft sample uses. `openssl pkcs12 -export` reads the PKCS#1
    # key tls_private_key emits directly, and OpenSSL 3.x output is accepted by KV
    # without -legacy. See ADR-0038.
    $pfxPwd = [System.Guid]::NewGuid().ToString('N')   # ephemeral; never logged or persisted
    & $opensslExe pkcs12 -export -inkey $keyPath -in $crtPath -out $pfxPath -passout "pass:$pfxPwd"
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $pfxPath)) {
        throw "openssl PFX packaging failed (exit $LASTEXITCODE)."
    }

    Write-Step "Importing '$CertName' into Key Vault '$KeyVaultName'"
    az keyvault certificate import `
        --vault-name $KeyVaultName `
        --name $CertName `
        --file $pfxPath `
        --password $pfxPwd `
        --output none
    if ($LASTEXITCODE -ne 0) {
        throw "az keyvault certificate import failed (exit $LASTEXITCODE)."
    }

    $secretUri = "https://$KeyVaultName.vault.azure.net/secrets/$CertName"
    Write-Step "Import succeeded."
    Write-Host "Secret URI (must match Bicep keyVaultUrl): $secretUri" -ForegroundColor Green
}
finally {
    # Securely remove key material. Overwrite then delete.
    foreach ($p in @($keyPath, $crtPath, $pfxPath)) {
        if (Test-Path -LiteralPath $p) {
            try {
                $len = (Get-Item -LiteralPath $p).Length
                if ($len -gt 0) {
                    [System.IO.File]::WriteAllBytes($p, (New-Object byte[] $len))
                }
            } catch { }
            Remove-Item -LiteralPath $p -Force -ErrorAction SilentlyContinue
        }
    }
    if (Test-Path -LiteralPath $tmpDir) {
        Remove-Item -LiteralPath $tmpDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}
